---
ansibleLint:
  configFile: ".ansible-lint.yml"
schedule:
  interval: "every minute"
  time: "09:00"
  # Use Indian Standard Time (UTC +05:30)
  timezone: "Asia/Calcutta"
open-pull-requests-limit: 3
